language: go

env:
  - GO111MODULE=on

go: 
 - "1.11.x"
 - "1.12.x"

before_install:                                                                 
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - go get github.com/mattn/goveralls
  - go test ./...

install: true

notifications:
  email: false

script:
  - $GOPATH/bin/goveralls -v -service=travis-ci
