version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  graphite-stats:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125/udp"
      - "8126:8126"
      - "32774:32774"
  eventlog_tcp_7220:
    image: flow/tcp_server
    ports:
      - "7220:7220"
    environment:
      TCP_SERVER_PORT: 7220
  eventlog_tcp_7221:
    image: flow/tcp_server
    ports:
      - "7221:7221"
    environment:
      TCP_SERVER_PORT: 7221
  eventlog_tcp_7222:
    image: flow/tcp_server
    ports:
      - "7222:7222"
    environment:
      TCP_SERVER_PORT: 7222
  eventlog_tcp_7223:
    image: flow/tcp_server
    ports:
      - "7223:7223"
    environment:
      TCP_SERVER_PORT: 7223
  eventlog_tcp_7224:
    image: flow/tcp_server
    ports:
      - "7224:7224"
    environment:
      TCP_SERVER_PORT: 7224
  eventlog_tcp_7225:
    image: flow/tcp_server
    ports:
      - "7225:7225"
    environment:
      TCP_SERVER_PORT: 7225
  eventlog_tcp_7226:
    image: flow/tcp_server
    ports:
      - "7226:7226"
    environment:
      TCP_SERVER_PORT: 7226
  eventlog_tcp_7227:
    image: flow/tcp_server
    ports:
      - "7227:7227"
    environment:
      TCP_SERVER_PORT: 7227
  eventlog_tcp_7228:
    image: flow/tcp_server
    ports:
      - "7228:7228"
    environment:
      TCP_SERVER_PORT: 7228
  eventlog_tcp_7229:
    image: flow/tcp_server
    ports:
      - "7229:7229"
    environment:
      TCP_SERVER_PORT: 7229
  eventlog_tcp_7230:
    image: flow/tcp_server
    ports:
      - "7230:7230"
    environment:
      TCP_SERVER_PORT: 7230
  eventlog_tcp_7231:
    image: flow/tcp_server
    ports:
      - "7231:7231"
    environment:
      TCP_SERVER_PORT: 7231
  eventlog_udp_7722:
    image: flow/udp_server
    ports:
      - "7722:7722/udp"
    environment:
      UDP_SERVER_PORT: 7722
  eventlog_udp_7723:
    image: flow/udp_server
    ports:
      - "7723:7723/udp"
    environment:
      UDP_SERVER_PORT: 7723
  eventlog_udp_7724:
    image: flow/udp_server
    ports:
      - "7724:7724/udp"
    environment:
      UDP_SERVER_PORT: 7724
  eventlog_udp_7725:
    image: flow/udp_server
    ports:
      - "7725:7725/udp"
    environment:
      UDP_SERVER_PORT: 7725
  eventlog_udp_7726:
    image: flow/udp_server
    ports:
      - "7726:7726/udp"
    environment:
      UDP_SERVER_PORT: 7726
  eventlog_udp_7727:
    image: flow/udp_server
    ports:
      - "7727:7727/udp"
    environment:
      UDP_SERVER_PORT: 7727
  
