components:
  evio_rcv:
    module: receiver.evio
    params:
      listeners:
        - tcp://localhost:3001
        - udp://localhost:3101
        - unix:///tmp/flow.sock
  stdout:
    module: sink.dumper
    params:
      out: STDOUT

pipeline:
  evio_rcv:
    connect: stdout