system:
  admin:
    enabled: true
    bind: :8080

actors:
  http_rcv:
    module: core.receiver.http
    params:
      bind: :7071
  dumper:
    module: core.sink
    params:
      bind: file://STDOUT

pipeline:
  http_rcv:
    connect: dumper
