system:
  maxprocs: 2
  admin:
    enabled: true
    bind_addr: :8080

components:
  http_rcv:
    module: receiver.http
    params:
      bind_addr: :7071
  router:
    module: link.router 
    params:
      routing_key: dest
  sink_a:
    module: sink.dumper
    params:
      out: a.out
  sink_b:
    module: sink.dumper
    params:
      out: b.out

pipeline:
  http_rcv:
    connect: router
  router:
    routes:
      a: sink_a
      b: sink_b
