system:
  max_proc: 4

components:
  tcp_rcv:
    module: receiver.tcp
    params:
      bind_addr: :3110
  meta_parser:
    module: link.meta_parser
  stdout:
    module: sink.dumper
    params:
      out: STDOUT

pipeline:
  tcp_rcv:
    connect: meta_parser
  meta_parser:
    connect: stdout