system:
  admin:
    enabled: true
    bind: :8080

actors:
  tcp_rcv:
    module: core.receiver.tcp
    params:
      bind: :3110
  stdout:
    module: core.sink
    params:
            bind: file://STDOUT

pipeline:
  tcp_rcv:
    connect: stdout
