system:
  maxprocs: 4
  admin:
    enabled: true
    bind_addr: :8080

components:
  unix_rcv:
    module: receiver.unix
    params:
      bind_addr: /tmp/flow.sock
      backend: evio
  demux:
    module: link.demux
  udp_sink:
    module: sink.udp
    params:
      bind_addr: :7722
  dumper:
    module: sink.dumper
    params:
      out: STDOUT

pipeline:
  unix_rcv:
    connect: demux
  demux:
    links:
      - udp_sink
      - dumper
