system:
  max_proc: 4

components:
  tcp_rcv:
    module: receiver.tcp
    params:
      bind_addr: :3110
      backend: evio
  meta_parser:
    module: link.meta_parser
  mpx:
    module: link.mpx
  tcp_sink_7222:
    module: sink.tcp
    params:
      bind_addr: localhost:7222
  tcp_sink_7223:
    module: sink.tcp
    params:
      bind_addr: localhost:7223
  tcp_sink_7224:
    module: sink.tcp
    params:
      bind_addr: localhost:7224
  tcp_sink_7225:
    module: sink.tcp
    params:
      bind_addr: localhost:7225
  tcp_sink_7226:
    module: sink.tcp
    params:
      bind_addr: localhost:7226
  tcp_sink_7227:
    module: sink.tcp
    params:
      bind_addr: localhost:7227

pipeline:
  tcp_rcv:
    connect: meta_parser
  meta_parser:
    connect: mpx
  mpx:
    links:
      - tcp_sink_7222
      - tcp_sink_7223
      - tcp_sink_7224
      - tcp_sink_7225
      - tcp_sink_7226
      - tcp_sink_7227