system:
  maxprocs: 4
  admin:
    enabled: true
    bind_addr: "localhost:4101"

components:
  udp_rcv:
    module: receiver.udp
    params:
      bind_addr: localhost:3101
      lib: evio
  stdout:
    module: sink.dumper
    params:
      out: STDOUT

pipeline:
  udp_rcv:
    connect: stdout