system:
  maxprocs: 4
  admin:
    enabled: true
    bind_addr: :8080

components:
  unix_rcv:
    module: receiver.unix
    params:
      bind_addr: /tmp/flow.sock
      backend: evio
  udp_sink:
    module: sink.udp
    params:
      bind_addr: :7722

pipeline:
  unix_rcv:
    connect: udp_sink
